### ISSUE TITLE
crash when joining an IRC channel with very many participants

### ISSUE THREAD

**Issue by the-wes** [jwise/naim#22]
connected to irc.freenode.net, issues /join #ubuntu, received:

 naim: hwprintf.c:655: vhhprintf: Assertion `len2 == len' failed.

naim has crashed.  Sorry about that!

Running naim 0.12.0-2011-10-18-0037 (development snapshot) for 15d 16:44m.
Aborted; partial symbolic backtrace:
0: naim(naim_faulthandler+0x26) [0x42e7b6]
1: /lib/libc.so.6 [0x7fa54cd50110]
2: /lib/libc.so.6(gsignal+0x3b) [0x7fa54cd5007b]
3: /lib/libc.so.6(abort+0x10e) [0x7fa54cd5184e]
4: /lib/libc.so.6(__assert_fail+0x104) [0x7fa54cd49af4]
5: naim(vhhprintf+0x230) [0x42d420]
6: naim(vhwprintf+0x5d) [0x42d4fd]
7: naim(window_echof+0x18b) [0x41b9cb]
8: naim [0x448a86]
9: naim [0x460384]
10: naim [0x45b5fe]
11: naim [0x4607cd]
12: naim [0x45ff37]
13: naim [0x45ffb4]
14: naim(lua_pcall+0x55) [0x4586b5]
15: naim(_call_hook+0xb6) [0x465b96]
16: naim [0x4662a1]
17: naim [0x41ed11]
18: naim [0x43dbf0]
19: naim [0x43e8a2]
20: naim(firetalk_select_custom+0x455) [0x43a4d5]
21: naim(main+0x7b0) [0x42f060]
22: /lib/libc.so.6(__libc_start_main+0xda) [0x7fa54cd3d4ca]
23: naim [0x40bb4a]

This information is not a replacement for running naim in gdb.  If you are interested in debugging this problem, please re-run naim within gdb and reproduce the fault.  When you are presented with the (gdb) prompt again, type "backtrace" to receive the full symbolic backtrace and file a bug at https://github.com/jwise/naim/issues.  If you can, leave the debug session open pending further instructions.

Aborted

**Comment by georgedorn** [comment]
Same problem here, on latest master.

**Comment by jwise** [comment]
Huh, I thought I fixed this a _long_ time ago.  Sigh.  I wonder what the fix was.

**Comment by georgedorn** [comment]
It works in https://github.com/nmlorg/naim (buried in naim/trunk) but that
client is ancient and still tries to connect to AIM via TOC2.

**Comment by jwise** [comment]
c783b53 fixes
